"""add parent_id to tweets

Revision ID: cd90752f5b4f
Revises: a7eaeef91692
Create Date: 2026-01-29 19:22:16.419937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd90752f5b4f'
down_revision: Union[str, Sequence[str], None] = 'a7eaeef91692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tweets_parent_id'), 'tweets', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'tweets', 'tweets', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_index(op.f('ix_tweets_parent_id'), table_name='tweets')
    op.drop_column('tweets', 'parent_id')
    # ### end Alembic commands ###
