import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./twitter_clone.db")
SECRET_KEY = os.getenv("SECRET_KEY", "CHANGE_ME_IN_PROD")
ALGORITHM = os.getenv("ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")


LOGIN_RATE_LIMIT = 5
LOGIN_RATE_WINDOW_SECOND = 60

SIGNUP_RATE_LIMIT = 1
SIGNUP_RATE_WINDOW_SECOND = 60

TWEET_RATE_LIMIT = 10
TWEET_RATE_WINDOW_SECOND = 60
